# Use the latest Node.js image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Install global dependencies (optional, for React development)
RUN npm install -g yarn --force

# Set the default entry point to bash
ENTRYPOINT ["/bin/bash"]