openapi: 3.0.0
info:
  title: Chat App API
  version: 1.0.0
  description: A simple API for a chat application.

servers:
  - url: https://api.chatapp.com
  - url: http://localhost:8080

paths:
  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "john_doe"
                password:
                  type: string
                  example: "secure_password"
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR..."

  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    username:
                      type: string
                      example: "john_doe"

  /users/{id}:
    get:
      summary: Get user details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  username:
                    type: string
                    example: "john_doe"

  /messages:
    get:
      summary: Get messages
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 101
                    sender_id:
                      type: integer
                      example: 1
                    content:
                      type: string
                      example: "Hello, world!"
                    timestamp:
                      type: string
                      format: date-time
                      example: "2024-12-22T14:55:00Z"

    post:
      summary: Send a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_id:
                  type: integer
                  example: 1
                content:
                  type: string
                  example: "Hello, how are you?"
      responses:
        '201':
          description: Message sent

  /ws:
    get:
      summary: WebSocket connection for real-time chat
      responses:
        '101':
          description: WebSocket connection established
